module.exports = {
  Auth: {
    Token: "s:string",
    Sign: "s:string",
    Cuit: "s:long",
    targetNSAlias: "tns",
    targetNamespace: "http://ar.gov.afip.dif.FEV1/",
  },
  FeCAEReq: {
    FeCabReq: {
      CantReg: "s:int",
      PtoVta: "s:int",
      CbteTipo: "s:int",
      targetNSAlias: "tns",
      targetNamespace: "http://ar.gov.afip.dif.FEV1/",
    },
    FeDetReq: {
      "FECAEDetRequest[]": {
        Concepto: "s:int",
        DocTipo: "s:int",
        DocNro: "s:long",
        CbteDesde: "s:long",
        CbteHasta: "s:long",
        CbteFch: "s:string",
        ImpTotal: "s:double",
        ImpTotConc: "s:double",
        ImpNeto: "s:double",
        ImpOpEx: "s:double",
        ImpTrib: "s:double",
        ImpIVA: "s:double",
        FchServDesde: "s:string",
        FchServHasta: "s:string",
        FchVtoPago: "s:string",
        MonId: "s:string",
        MonCotiz: "s:double",
        CbtesAsoc: {
          "CbteAsoc[]": {
            Tipo: "s:int",
            PtoVta: "s:int",
            Nro: "s:long",
            Cuit: "s:string",
            CbteFch: "s:string",
            targetNSAlias: "tns",
            targetNamespace: "http://ar.gov.afip.dif.FEV1/",
          },
          targetNSAlias: "tns",
          targetNamespace: "http://ar.gov.afip.dif.FEV1/",
        },
        Tributos: {
          "Tributo[]": {
            Id: "s:short",
            Desc: "s:string",
            BaseImp: "s:double",
            Alic: "s:double",
            Importe: "s:double",
            targetNSAlias: "tns",
            targetNamespace: "http://ar.gov.afip.dif.FEV1/",
          },
          targetNSAlias: "tns",
          targetNamespace: "http://ar.gov.afip.dif.FEV1/",
        },
        Iva: {
          "AlicIva[]": {
            Id: "s:int",
            BaseImp: "s:double",
            Importe: "s:double",
            targetNSAlias: "tns",
            targetNamespace: "http://ar.gov.afip.dif.FEV1/",
          },
          targetNSAlias: "tns",
          targetNamespace: "http://ar.gov.afip.dif.FEV1/",
        },
        Opcionales: {
          "Opcional[]": {
            Id: "s:string",
            Valor: "s:string",
            targetNSAlias: "tns",
            targetNamespace: "http://ar.gov.afip.dif.FEV1/",
          },
          targetNSAlias: "tns",
          targetNamespace: "http://ar.gov.afip.dif.FEV1/",
        },
        Compradores: {
          "Comprador[]": {
            DocTipo: "s:int",
            DocNro: "s:long",
            Porcentaje: "s:double",
            targetNSAlias: "tns",
            targetNamespace: "http://ar.gov.afip.dif.FEV1/",
          },
          targetNSAlias: "tns",
          targetNamespace: "http://ar.gov.afip.dif.FEV1/",
        },
        PeriodoAsoc: {
          FchDesde: "s:string",
          FchHasta: "s:string",
          targetNSAlias: "tns",
          targetNamespace: "http://ar.gov.afip.dif.FEV1/",
        },
        targetNSAlias: "tns",
        targetNamespace: "http://ar.gov.afip.dif.FEV1/",
      },
      targetNSAlias: "tns",
      targetNamespace: "http://ar.gov.afip.dif.FEV1/",
    },
    targetNSAlias: "tns",
    targetNamespace: "http://ar.gov.afip.dif.FEV1/",
  },
};
